### ISSUE TITLE
Missing cities from ParkAPI

### ISSUE THREAD

**Issue by jklmnn** [ParkenDD/ParkAPI2-sources#17]
This issue exists to track the split between the sources available in ParkAPI and ParkAPI2. It will include already opened PRs (and link to them).

Missing:

- [x] Aachen (https://github.com/ParkenDD/ParkAPI2-sources/pull/20)
- [x] Hamburg (https://github.com/ParkenDD/ParkAPI2-sources/pull/11)
- [x] Hanau (https://github.com/ParkenDD/ParkAPI2-sources/pull/8)
- [x] Heilbronn (https://github.com/ParkenDD/ParkAPI2-sources/pull/7)
- [x] Karlsruhe (https://github.com/ParkenDD/ParkAPI2-sources/pull/10)
- [x] Rosenheim (https://github.com/ParkenDD/ParkAPI2-sources/pull/4)

**Comment by hbruch** [comment]
Outstanding PRs: 
* Aachen (#20)
* Rosenheim (#4)

**Comment by hbruch** [comment]
With the merge of #10, all cities that were still missing are now merged
