### ISSUE TITLE
Cities currently broken in ParkAPI

### ISSUE THREAD

**Issue by jklmnn** [ParkenDD/ParkAPI2-sources#18]
This issue aims to track the cities currently broken in ParkAPI (1). As they will not be fixed there we should check that they're fixed here.

- [x] Heilbronn (https://github.com/ParkenDD/ParkAPI2-sources/pull/7)
- [x] Hanau (https://github.com/ParkenDD/ParkAPI2-sources/pull/8)
- [x] Köln (is not listed in #17, to be checked if it works here)
- [x] Lübeck (https://github.com/ParkenDD/ParkAPI2-sources/pull/9)
- [x] Rosenheim (#17)
- [x] Regensburg (not listed in #17, to be checked if it works here)

**Comment by hbruch** [comment]
Regensburg works, write-geojson reproduces current geojson.
